Meghan-Harris_blog-entry
rladies/awesome-rladies-blogs pull request #44
Opened 2023-02-22 14:38 UTC by Meghansaha

Not sure if adding mastodon is accepted? Added it just in case.

2023-02-24 09:53 UTC, drmowinckels requested changes
Thank you for submitting!!

Can you please also change the name of the file to:
thetidytrekker.com.json

This is the best assurance we have of keeping json-filenames unique

2023-02-24 09:53 UTC, drmowinckels commented on blogs/your-blog-url.com.json
> +  "language": "en (required)", //required
```suggestion
  "language": "en",
```

2023-02-24 09:53 UTC, drmowinckels commented on blogs/your-blog-url.com.json
> +      "name": "Meghan Harris", //required
```suggestion
      "name": "Meghan Harris",

2023-02-24 09:53 UTC, drmowinckels commented on blogs/your-blog-url.com.json
> +  "authors": [ //required
```suggestion
  "authors": [

2023-02-25 02:52 UTC, Meghansaha reviewed
accepted all and changed file name

2023-02-27 08:42 UTC, merged